07_review_decorator/app1/urls.py
from django.urls import path
from .import views

app_name = 'app1'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/update', views.update, name='update'),
]

07_review_decorator/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
]

07_review_decorator/app1/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

07_review_decorator/app1/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = '__all__'

07_review_decorator/app1/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .models import Article
from .forms import ArticleForm

@require_safe
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'app1/index.html', context)

@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('app1:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'app1/create.html', context)

@require_safe
def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article': article
    }
    return render(request, 'app1/detail.html', context)

@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect('app1:index')

@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('app1:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'app1/update.html', context)

07_review_decorator/app1/templates/app1/create.html
{% extends 'base.html' %}

{% block content %}
<h3>create</h3>

<form action="{% url 'app1:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

{% endblock content %}

07_review_decorator/app1/templates/app1/detail.html
{% extends 'base.html' %}

{% block content %}
<p>번호 : {{ article.pk }}</p>
<p>작성 : {{ article.created_at }}</p>
<p>수정 : {{ article.updated_at }}</p>
<p>제목 : {{ article.title }}</p>
<p>내용 : {{ article.content }}</p>
<hr>
<a href="{% url 'app1:index' %}">app1</a>
<br>
<form action="{% url 'app1:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button>삭제</button>
</form>

<a href="{% url 'app1:update' article.pk %}">update</a>

{% endblock content %}

07_review_decorator/app1/templates/app1/index.html
{% extends 'base.html' %}

{% block content %}

<h3>app1</h3>
<a href="{% url 'app1:create' %}">[create]</a>
<br>
{% for article in articles %}
<a href="{% url 'app1:detail' article.pk %}">
    <p>{{ article.pk }}. {{ article.title }}</p>
</a>
{% endfor %}

{% endblock content %}

07_review_decorator/app1/templates/app1/update.html
{% extends 'base.html' %}

{% block content %}
<h3>update</h3>

<form action="{% url 'app1:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit'>
</form>

<a href="{% url 'app1:detail' article.pk %}">back</a>

{% endblock content %}